/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 1
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_PERCENT_AT = 1,
  anon_sym_PERCENT_GT = 2,
  anon_sym_params = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_extends = 6,
  sym_parameter_list = 7,
  aux_sym_type_reference_token1 = 8,
  anon_sym_LT_PERCENT = 9,
  sym_interpolation_content = 10,
  anon_sym_LT_PERCENT_EQ = 11,
  anon_sym_DOLLAR_LBRACE = 12,
  anon_sym_RBRACE = 13,
  sym_content = 14,
  sym_template = 15,
  sym_directive = 16,
  sym__directive_body = 17,
  sym_type_reference = 18,
  sym_scriptlet = 19,
  sym_scriptlet_content = 20,
  sym_expression = 21,
  sym_interpolation = 22,
  aux_sym_template_repeat1 = 23,
  alias_sym_expression_content = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_PERCENT_AT] = "<%@",
  [anon_sym_PERCENT_GT] = "%>",
  [anon_sym_params] = "params",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_extends] = "extends",
  [sym_parameter_list] = "parameter_list",
  [aux_sym_type_reference_token1] = "type_reference_token1",
  [anon_sym_LT_PERCENT] = "<%",
  [sym_interpolation_content] = "interpolation_content",
  [anon_sym_LT_PERCENT_EQ] = "<%=",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_RBRACE] = "}",
  [sym_content] = "content",
  [sym_template] = "template",
  [sym_directive] = "directive",
  [sym__directive_body] = "_directive_body",
  [sym_type_reference] = "type_reference",
  [sym_scriptlet] = "scriptlet",
  [sym_scriptlet_content] = "scriptlet_content",
  [sym_expression] = "expression",
  [sym_interpolation] = "interpolation",
  [aux_sym_template_repeat1] = "template_repeat1",
  [alias_sym_expression_content] = "expression_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_PERCENT_AT] = anon_sym_LT_PERCENT_AT,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [anon_sym_params] = anon_sym_params,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_extends] = anon_sym_extends,
  [sym_parameter_list] = sym_parameter_list,
  [aux_sym_type_reference_token1] = aux_sym_type_reference_token1,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [sym_interpolation_content] = sym_interpolation_content,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_content] = sym_content,
  [sym_template] = sym_template,
  [sym_directive] = sym_directive,
  [sym__directive_body] = sym__directive_body,
  [sym_type_reference] = sym_type_reference,
  [sym_scriptlet] = sym_scriptlet,
  [sym_scriptlet_content] = sym_scriptlet_content,
  [sym_expression] = sym_expression,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [alias_sym_expression_content] = alias_sym_expression_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_params] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_type_reference_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_interpolation_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__directive_body] = {
    .visible = false,
    .named = true,
  },
  [sym_type_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_scriptlet] = {
    .visible = true,
    .named = true,
  },
  [sym_scriptlet_content] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_expression_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_expression_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_scriptlet_content, 2,
    sym_scriptlet_content,
    alias_sym_expression_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '$', 15,
        '%', 3,
        '(', 22,
        ')', 23,
        '<', 2,
        'e', 14,
        'p', 4,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 'x') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '{') ADVANCE(33);
      END_STATE();
    case 16:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 17:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(26);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_AT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_params);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_parameter_list);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_parameter_list);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_type_reference_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_type_reference_token1);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '@') ADVANCE(19);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_interpolation_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_interpolation_content);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_PERCENT_AT] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_params] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(14),
    [sym_directive] = STATE(2),
    [sym_scriptlet] = STATE(2),
    [sym_expression] = STATE(2),
    [sym_interpolation] = STATE(2),
    [aux_sym_template_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_PERCENT_AT] = ACTIONS(5),
    [anon_sym_LT_PERCENT] = ACTIONS(7),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(9),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(11),
    [sym_content] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      anon_sym_LT_PERCENT_AT,
    ACTIONS(7), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(9), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(11), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_content,
    STATE(3), 5,
      sym_directive,
      sym_scriptlet,
      sym_expression,
      sym_interpolation,
      aux_sym_template_repeat1,
  [26] = 7,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_LT_PERCENT_AT,
    ACTIONS(24), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(27), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(30), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(33), 1,
      sym_content,
    STATE(3), 5,
      sym_directive,
      sym_scriptlet,
      sym_expression,
      sym_interpolation,
      aux_sym_template_repeat1,
  [52] = 2,
    ACTIONS(38), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(36), 5,
      sym_content,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
  [63] = 2,
    ACTIONS(42), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(40), 5,
      sym_content,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
  [74] = 2,
    ACTIONS(46), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(44), 5,
      sym_content,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
  [85] = 2,
    ACTIONS(50), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(48), 5,
      sym_content,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
  [96] = 2,
    ACTIONS(54), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(52), 5,
      sym_content,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_DOLLAR_LBRACE,
  [107] = 3,
    ACTIONS(56), 1,
      anon_sym_params,
    ACTIONS(58), 1,
      anon_sym_extends,
    STATE(15), 1,
      sym__directive_body,
  [117] = 3,
    ACTIONS(60), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(62), 1,
      aux_sym_type_reference_token1,
    STATE(18), 1,
      sym_scriptlet_content,
  [127] = 2,
    ACTIONS(64), 1,
      aux_sym_type_reference_token1,
    STATE(21), 1,
      sym_type_reference,
  [134] = 2,
    ACTIONS(62), 1,
      aux_sym_type_reference_token1,
    STATE(23), 1,
      sym_scriptlet_content,
  [141] = 1,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
  [145] = 1,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
  [149] = 1,
    ACTIONS(70), 1,
      anon_sym_PERCENT_GT,
  [153] = 1,
    ACTIONS(72), 1,
      sym_interpolation_content,
  [157] = 1,
    ACTIONS(74), 1,
      anon_sym_PERCENT_GT,
  [161] = 1,
    ACTIONS(76), 1,
      anon_sym_PERCENT_GT,
  [165] = 1,
    ACTIONS(78), 1,
      sym_parameter_list,
  [169] = 1,
    ACTIONS(80), 1,
      anon_sym_PERCENT_GT,
  [173] = 1,
    ACTIONS(82), 1,
      anon_sym_PERCENT_GT,
  [177] = 1,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
  [181] = 1,
    ACTIONS(86), 1,
      anon_sym_PERCENT_GT,
  [185] = 1,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
  [189] = 1,
    ACTIONS(90), 1,
      anon_sym_PERCENT_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 63,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 85,
  [SMALL_STATE(8)] = 96,
  [SMALL_STATE(9)] = 107,
  [SMALL_STATE(10)] = 117,
  [SMALL_STATE(11)] = 127,
  [SMALL_STATE(12)] = 134,
  [SMALL_STATE(13)] = 141,
  [SMALL_STATE(14)] = 145,
  [SMALL_STATE(15)] = 149,
  [SMALL_STATE(16)] = 153,
  [SMALL_STATE(17)] = 157,
  [SMALL_STATE(18)] = 161,
  [SMALL_STATE(19)] = 165,
  [SMALL_STATE(20)] = 169,
  [SMALL_STATE(21)] = 173,
  [SMALL_STATE(22)] = 177,
  [SMALL_STATE(23)] = 181,
  [SMALL_STATE(24)] = 185,
  [SMALL_STATE(25)] = 189,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scriptlet, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scriptlet, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 1),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 1),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scriptlet, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scriptlet, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [68] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scriptlet_content, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_reference, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_body, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_body, 4, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_content] = sym_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_gosu_template_external_scanner_create(void);
void tree_sitter_gosu_template_external_scanner_destroy(void *);
bool tree_sitter_gosu_template_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_gosu_template_external_scanner_serialize(void *, char *);
void tree_sitter_gosu_template_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gosu_template(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_gosu_template_external_scanner_create,
      tree_sitter_gosu_template_external_scanner_destroy,
      tree_sitter_gosu_template_external_scanner_scan,
      tree_sitter_gosu_template_external_scanner_serialize,
      tree_sitter_gosu_template_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "gosu_template",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
